### ISSUE TITLE
윈도우용 안드로이드 스튜디오 psf 홈 디렉토리 문제

### ISSUE THREAD

**Issue by dalinaum** [dalinaum/dalinaum.github.io#2]
윈도우용 안드로이드 스튜디오에서 psf 홈 디렉토리를 쓸 수 없는 문제 수정. (그래들의 문제?)

**Comment by dalinaum** [comment]
```
Error:Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.2.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(File.java:423)
	at org.gradle.internal.classloader.ClasspathUtil.getClasspathForClass(ClasspathUtil.java:67)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.findDistDir(DefaultModuleRegistry.java:75)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.<init>(DefaultModuleRegistry.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:44)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.daemon.bootstrap.GradleDaemon.main(GradleDaemon.java:22)
```
